/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author Marco
 */
public class AdminFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminFrame.class.getName());

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        
        initComponents();
        setupFlatLafStyles();
        setLocationRelativeTo(null);
        adminDashboardButtonActionPerformed(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        addFoodButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        adminDashboardButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        buttonPanel.setBackground(new java.awt.Color(102, 204, 255));

        addFoodButton.setText("Add Food");
        addFoodButton.addActionListener(this::addFoodButtonActionPerformed);

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(this::logOutButtonActionPerformed);

        adminDashboardButton.setText("Dashboard");
        adminDashboardButton.addActionListener(this::adminDashboardButtonActionPerformed);

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addFoodButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminDashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(adminDashboardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFoodButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(logOutButton)
                .addGap(25, 25, 25))
        );

        getContentPane().add(buttonPanel);

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));
        mainPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupFlatLafStyles() {
        // Sidebar panel background and clean right border
        buttonPanel.putClientProperty(FlatClientProperties.STYLE, ""
                + "background: $Menu.background;"
                + "border: 0,0,0,1, $Component.borderColor;");

        // Common styling for sidebar buttons (rounded corners, padded text, left alignment)
        String navButtonStyle = ""
                + "arc: 10;"
                + "borderWidth: 0;"
                + "focusWidth: 0;"
                + "margin: 8,14,8,14;"
                + "align: left;";

        adminDashboardButton.putClientProperty(FlatClientProperties.STYLE, navButtonStyle);
        addFoodButton.putClientProperty(FlatClientProperties.STYLE, navButtonStyle);

        // Logout button styled with a modern outline look
        logOutButton.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc: 10;"
                + "buttonType: outline;"
                + "margin: 8,14,8,14;"
                + "align: left;");
    }
    
    private void addFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodButtonActionPerformed
        // TODO add your handling code here:
        
        AdminAddFoodPanel addFoodPanel = new AdminAddFoodPanel();
        
        mainPanel.removeAll();
        mainPanel.add(addFoodPanel);
        mainPanel.revalidate();
        mainPanel.repaint();
        
    }//GEN-LAST:event_addFoodButtonActionPerformed

    private void adminDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDashboardButtonActionPerformed
        // TODO add your handling code here:
        
        AdminDashboardPanel adminDashboard = new AdminDashboardPanel();
        
        mainPanel.removeAll();
        mainPanel.add(adminDashboard);
        mainPanel.revalidate();
        mainPanel.repaint();
        
    }//GEN-LAST:event_adminDashboardButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
        
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(logOutButton);
        if (parentWindow != null) {
            parentWindow.dispose();
        }
    }//GEN-LAST:event_logOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFoodButton;
    private javax.swing.JButton adminDashboardButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
