/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation;

import dto.CreateFoodDto;
import dto.CreateStallDto;
import dto.FoodResponseDto;
import dto.StallResponseDto;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import service.Controller;

/**
 *
 * @author Marco
 */
public class AdminAddFoodPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminAddFoodPanel
     */
    private Controller controller = new Controller();
    private String stallPhotoFilePath = "no_photo_attached";
    private String foodPhotoFilePath = "no_photo_attached";

    public AdminAddFoodPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        addFoodButton = new javax.swing.JButton();
        stallPhotoPanel = new javax.swing.JPanel();
        photoPreviewLabel = new javax.swing.JLabel();
        uploadStallPhotoButton = new javax.swing.JButton();
        stallField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        saveStall = new javax.swing.JButton();
        stallFieldForAddFood = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        getStallButton = new javax.swing.JButton();
        stallIdField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        clearFieldsButton = new javax.swing.JButton();
        uploadFoodPhotoButton1 = new javax.swing.JButton();
        foodPhotoPanel = new javax.swing.JPanel();
        foodPhotoPreviewLabel = new javax.swing.JLabel();

        jLabel1.setText("Name");

        jLabel3.setText("Price");

        priceField.addActionListener(this::priceFieldActionPerformed);

        addFoodButton.setText("Add Food");
        addFoodButton.addActionListener(this::addFoodButtonActionPerformed);

        stallPhotoPanel.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout stallPhotoPanelLayout = new javax.swing.GroupLayout(stallPhotoPanel);
        stallPhotoPanel.setLayout(stallPhotoPanelLayout);
        stallPhotoPanelLayout.setHorizontalGroup(
            stallPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stallPhotoPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(photoPreviewLabel)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        stallPhotoPanelLayout.setVerticalGroup(
            stallPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stallPhotoPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(photoPreviewLabel)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        uploadStallPhotoButton.setText("Upload Photo");
        uploadStallPhotoButton.addActionListener(this::uploadStallPhotoButtonActionPerformed);

        stallField.addActionListener(this::stallFieldActionPerformed);

        jLabel4.setText("Stall");

        saveStall.setText("Save Stall");
        saveStall.addActionListener(this::saveStallActionPerformed);

        stallFieldForAddFood.addActionListener(this::stallFieldForAddFoodActionPerformed);

        jLabel5.setText("Stall Name");

        getStallButton.setText("Get Stall");
        getStallButton.addActionListener(this::getStallButtonActionPerformed);

        jLabel6.setText("Stall ID");

        clearFieldsButton.setText("Clear Fields");
        clearFieldsButton.addActionListener(this::clearFieldsButtonActionPerformed);

        uploadFoodPhotoButton1.setText("Upload Photo");
        uploadFoodPhotoButton1.addActionListener(this::uploadFoodPhotoButton1ActionPerformed);

        foodPhotoPanel.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout foodPhotoPanelLayout = new javax.swing.GroupLayout(foodPhotoPanel);
        foodPhotoPanel.setLayout(foodPhotoPanelLayout);
        foodPhotoPanelLayout.setHorizontalGroup(
            foodPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodPhotoPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(foodPhotoPreviewLabel)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        foodPhotoPanelLayout.setVerticalGroup(
            foodPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodPhotoPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(foodPhotoPreviewLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(stallField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveStall))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stallPhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uploadStallPhotoButton))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addFoodButton)
                                .addGap(360, 360, 360))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(foodNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(24, 24, 24))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(getStallButton)
                                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(stallFieldForAddFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(stallIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uploadFoodPhotoButton1)
                                    .addComponent(foodPhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearFieldsButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stallPhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uploadStallPhotoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stallFieldForAddFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stallIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getStallButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(foodNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(foodPhotoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(uploadFoodPhotoButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(addFoodButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stallField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveStall)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(clearFieldsButton)
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void uploadStallPhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadStallPhotoButtonActionPerformed
        // TODO add your handling code here:

        JFrame frame = new JFrame("Photo Picker Example");

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select a Photo");

        //restrict the file types visible in the explorer window
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images (*.png, *.jpg, *.jpeg)", "png", "jpg", "jpeg");
        fileChooser.setFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false); // Hide "All Files" option

        //open File Explorer
        int response = fileChooser.showOpenDialog(frame);

        //check if the user actually clicked "Open/Save" instead of "Cancel"
        if (response == JFileChooser.APPROVE_OPTION) {

            File selectedFile = fileChooser.getSelectedFile();

            //get the file selected by the user
            stallPhotoFilePath = selectedFile.getAbsolutePath();

            //convert the file path into an ImageIcon
            ImageIcon photo = new ImageIcon(selectedFile.getAbsolutePath());

            //scale down to preview JLabel
            Image scaledImage = photo.getImage().getScaledInstance(289, 267, Image.SCALE_SMOOTH);

            //display the image on the preview JLabel
            photoPreviewLabel.setIcon(new ImageIcon(scaledImage));

            //display confirmation
            JOptionPane.showMessageDialog(frame, "Picked: " + selectedFile.getName());

        }

    }//GEN-LAST:event_uploadStallPhotoButtonActionPerformed

    private void stallFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stallFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stallFieldActionPerformed

    private void saveStallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStallActionPerformed
        // TODO add your handling code here:
        CreateStallDto dto = new CreateStallDto();
        dto.setName(stallField.getText());
        dto.setPhotoFilePath(stallPhotoFilePath);

        try {
            StallResponseDto returnedStall = controller.saveStall(dto);
        } catch (IOException ex) {
            System.getLogger(AdminAddFoodPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (InterruptedException ex) {
            System.getLogger(AdminAddFoodPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_saveStallActionPerformed

    private void addFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodButtonActionPerformed
        // TODO add your handling code here:

        String name = foodNameField.getText();
        double price = Double.parseDouble(priceField.getText());
        long stallId = Long.parseLong(stallIdField.getText());

        CreateFoodDto food = new CreateFoodDto(name, price, stallId, foodPhotoFilePath);

        try {
            FoodResponseDto returnedFood = controller.saveFood(food);
        } catch (IOException ex) {
            System.getLogger(AdminAddFoodPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (InterruptedException ex) {
            System.getLogger(AdminAddFoodPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_addFoodButtonActionPerformed

    private void getStallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStallButtonActionPerformed
        // TODO add your handling code here:
        String stallName = stallFieldForAddFood.getText();

        try {
            StallResponseDto returnedStall = controller.getStallByName(stallName);
            stallFieldForAddFood.setText(returnedStall.getName());
            stallIdField.setText(String.valueOf(returnedStall.getId()));
        } catch (IOException ex) {
            System.getLogger(AdminAddFoodPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (InterruptedException ex) {
            System.getLogger(AdminAddFoodPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_getStallButtonActionPerformed

    private void clearFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldsButtonActionPerformed
        // TODO add your handling code here:
        stallField.setText("");
        stallFieldForAddFood.setText("");
        stallIdField.setText("");
        foodNameField.setText("");
        priceField.setText("");

        stallPhotoFilePath = "no_photo_attached";
        foodPhotoFilePath = "no_photo_attached";

        photoPreviewLabel.setIcon(null);
        foodPhotoPreviewLabel.setIcon(null);
    }//GEN-LAST:event_clearFieldsButtonActionPerformed

    private void uploadFoodPhotoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadFoodPhotoButton1ActionPerformed
        // TODO add your handling code here:

        JFrame frame = new JFrame("Photo Picker Example");

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select a Photo");

        //restrict the file types visible in the explorer window
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images (*.png, *.jpg, *.jpeg)", "png", "jpg", "jpeg");
        fileChooser.setFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false); // Hide "All Files" option

        //open File Explorer
        int response = fileChooser.showOpenDialog(frame);

        //check if the user actually clicked "Open/Save" instead of "Cancel"
        if (response == JFileChooser.APPROVE_OPTION) {

            File selectedFile = fileChooser.getSelectedFile();

            //get the file selected by the user
            foodPhotoFilePath = selectedFile.getAbsolutePath();

            //convert the file path into an ImageIcon
            ImageIcon photo = new ImageIcon(selectedFile.getAbsolutePath());

            //scale down to preview JLabel
            Image scaledImage = photo.getImage().getScaledInstance(289, 267, Image.SCALE_SMOOTH);

            //display the image on the preview JLabel
            foodPhotoPreviewLabel.setIcon(new ImageIcon(scaledImage));

            //display confirmation
            JOptionPane.showMessageDialog(frame, "Picked: " + selectedFile.getName());

        }

    }//GEN-LAST:event_uploadFoodPhotoButton1ActionPerformed

    private void stallFieldForAddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stallFieldForAddFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stallFieldForAddFoodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFoodButton;
    private javax.swing.JButton clearFieldsButton;
    private javax.swing.JTextField foodNameField;
    private javax.swing.JPanel foodPhotoPanel;
    private javax.swing.JLabel foodPhotoPreviewLabel;
    private javax.swing.JButton getStallButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel photoPreviewLabel;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton saveStall;
    private javax.swing.JTextField stallField;
    private javax.swing.JTextField stallFieldForAddFood;
    private javax.swing.JTextField stallIdField;
    private javax.swing.JPanel stallPhotoPanel;
    private javax.swing.JButton uploadFoodPhotoButton1;
    private javax.swing.JButton uploadStallPhotoButton;
    // End of variables declaration//GEN-END:variables
}
