/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation;

import dto.CreateReviewDto;
import dto.FoodResponseDto;
import dto.ReviewResponseDto;
import java.awt.Container;
import java.awt.Image;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import service.Controller;
import service.Service;
import com.formdev.flatlaf.FlatClientProperties;
import service.UserSession;

/**
 *
 * @author Marco
 */
public class FoodItemPanel extends javax.swing.JPanel {

    private Controller controller = new Controller();
    private final FoodResponseDto food;
    private final String stallName;
    private final Service service = new Service();

    /**
     * Creates new form FoodItemPanel
     */
    public FoodItemPanel(FoodResponseDto food, String stallName) {
        this.food = food;
        this.stallName = stallName;
        initComponents();
        deleteFoodButton.setVisible(UserSession.isLoggedIn());
        setupFlatLafStyles();

        String foodName = food.getName();
        foodNameLabel.setText(foodName);

        //convert the file path into an ImageIcon
        ImageIcon photo = new ImageIcon(food.getFoodPhotoFilePath());

        //scale down to preview JLabel
        Image scaledImage = photo.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);

        //display the image on the preview JLabel
        foodPhotoLabel.setIcon(new ImageIcon(scaledImage));

        String price = String.valueOf(food.getPrice());
        foodPriceLabel.setText(price);

        stallNameLabel.setText(stallName);

        loadReviews();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodNameLabel = new javax.swing.JLabel();
        foodPhotoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        foodPriceLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stallNameLabel = new javax.swing.JLabel();
        priceScoreField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tasteScoreField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cleanlinessScoreField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        commentField = new javax.swing.JTextField();
        sendReviewButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        studentNumberField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        deleteFoodButton = new javax.swing.JButton();
        studentNicknameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reviewList = new javax.swing.JList<>();

        foodNameLabel.setText("Food");

        foodPhotoLabel.setText("Food photo");

        jLabel1.setText("Price:");

        foodPriceLabel.setText("foodPrice");

        jLabel2.setText("Sold By:");

        stallNameLabel.setText("Stall");

        jLabel3.setText("Price score:");

        jLabel4.setText("Taste Score:");

        jLabel5.setText("Cleanliness Score");

        jLabel6.setText("Comment (Optional):");

        sendReviewButton.setText("Send Review");
        sendReviewButton.addActionListener(this::sendReviewButtonActionPerformed);

        jLabel7.setText("Student Number:");

        jLabel8.setText("Add a review:");

        deleteFoodButton.setText("Delete Food");
        deleteFoodButton.addActionListener(this::deleteFoodButtonActionPerformed);

        jLabel9.setText("Nickname:");

        jLabel10.setText("Reviews:");

        jScrollPane1.setViewportView(reviewList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(foodPhotoLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(foodNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(foodPriceLabel))
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stallNameLabel)
                                            .addComponent(jLabel2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(79, 79, 79)
                                        .addComponent(deleteFoodButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(studentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(studentNicknameField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(priceScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tasteScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(cleanlinessScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(48, 48, 48)))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(commentField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sendReviewButton)))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foodPriceLabel)
                            .addComponent(stallNameLabel))
                        .addGap(13, 13, 13)
                        .addComponent(foodPhotoLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(deleteFoodButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentNicknameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(priceScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tasteScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cleanlinessScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(commentField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sendReviewButton))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setupFlatLafStyles() {
        String inputFieldStyle = ""
                + "arc: 10;"
                + "margin: 4,8,4,8;";

        studentNumberField.putClientProperty(FlatClientProperties.STYLE, inputFieldStyle);
        studentNicknameField.putClientProperty(FlatClientProperties.STYLE, inputFieldStyle);
        priceScoreField.putClientProperty(FlatClientProperties.STYLE, inputFieldStyle);
        tasteScoreField.putClientProperty(FlatClientProperties.STYLE, inputFieldStyle);
        cleanlinessScoreField.putClientProperty(FlatClientProperties.STYLE, inputFieldStyle);
        commentField.putClientProperty(FlatClientProperties.STYLE, inputFieldStyle);

        // Placeholders
        studentNumberField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "6-digit ID");
        studentNicknameField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nickname");
        priceScoreField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "1-5");
        tasteScoreField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "1-5");
        cleanlinessScoreField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "1-5");
        commentField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Write a comment...");

        // Clear buttons for text fields
        studentNumberField.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
        studentNicknameField.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);

        // Buttons
        sendReviewButton.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc: 10;"
                + "buttonType: accent;"
                + "margin: 6,14,6,14;");

        deleteFoodButton.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc: 10;"
                + "buttonType: outline;"
                + "borderColor: #E53935;"
                + "foreground: #E53935;"
                + "margin: 6,14,6,14;");

        // Typography
        foodNameLabel.putClientProperty(FlatClientProperties.STYLE, "font: bold +6");
        foodPriceLabel.putClientProperty(FlatClientProperties.STYLE, "font: bold +2");
        stallNameLabel.putClientProperty(FlatClientProperties.STYLE, "font: bold +2");

        // ScrollPane border rounding
        jScrollPane1.putClientProperty(FlatClientProperties.STYLE, "arc: 10");
    }

    private void loadReviews() {
        try {
            // Retrieve reviews associated with this food ID from controller
            java.util.List<ReviewResponseDto> reviews = controller.getReviewsByFood(food.getId());

            javax.swing.DefaultListModel<ReviewResponseDto> listModel = new javax.swing.DefaultListModel<>();
            for (ReviewResponseDto review : reviews) {
                listModel.addElement(review);
            }

            reviewList.setModel(listModel);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load reviews: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(this, "Review loading interrupted.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void sendReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendReviewButtonActionPerformed
        // TODO add your handling code here:

        int studentNumber = 0;
        int priceScore = 0;
        int tasteScore = 0;
        int cleanlinessScore = 0;

        try {
            studentNumber = service.validateIntegerData(studentNumberField, "Student Number");
            priceScore = service.validateIntegerData(priceScoreField, "Price Score");
            tasteScore = service.validateIntegerData(tasteScoreField, "Taste Score");
            cleanlinessScore = service.validateIntegerData(cleanlinessScoreField, "Cleanliness Score");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        }

        String comment = commentField.getText().trim();
        String nickname = studentNicknameField.getText().trim();

        if (comment.isEmpty() || nickname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please include a student number and nickname.");
            return;
        }

        CreateReviewDto dto = new CreateReviewDto(studentNumber, nickname, priceScore, tasteScore, cleanlinessScore, comment, food.getId());

        studentNumberField.setText("");
        priceScoreField.setText("");
        tasteScoreField.setText("");
        cleanlinessScoreField.setText("");
        commentField.setText("");
        studentNicknameField.setText("");

        try {
            ReviewResponseDto returnedReview = controller.saveReview(dto);
            JOptionPane.showMessageDialog(this, "Successfully saved Review.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Saving Food", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(this, "The operation was interrupted.", "Operation Interrupted", javax.swing.JOptionPane.WARNING_MESSAGE);
        }

        loadReviews();
    }//GEN-LAST:event_sendReviewButtonActionPerformed

    private void deleteFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFoodButtonActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
                FoodItemPanel.this,
                "Are you sure you want to delete this food item?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // 2. Delete the stall
                controller.deleteFood(food.getId());
                JOptionPane.showMessageDialog(FoodItemPanel.this, "Food deleted successfully.");

                // 3. Go back to StallsPanel
                Container parentContainer = FoodItemPanel.this.getParent();
                if (parentContainer != null) {
                    parentContainer.removeAll();
                    parentContainer.add(new FoodsPanel(food.getStallId(), stallName));
                    parentContainer.revalidate();
                    parentContainer.repaint();
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(FoodItemPanel.this, ex.getMessage(), "Error deleting Stall", JOptionPane.ERROR_MESSAGE);
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(FoodItemPanel.this, "Operation interrupted.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteFoodButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cleanlinessScoreField;
    private javax.swing.JTextField commentField;
    private javax.swing.JButton deleteFoodButton;
    private javax.swing.JLabel foodNameLabel;
    private javax.swing.JLabel foodPhotoLabel;
    private javax.swing.JLabel foodPriceLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField priceScoreField;
    private javax.swing.JList<dto.ReviewResponseDto> reviewList;
    private javax.swing.JButton sendReviewButton;
    private javax.swing.JLabel stallNameLabel;
    private javax.swing.JTextField studentNicknameField;
    private javax.swing.JTextField studentNumberField;
    private javax.swing.JTextField tasteScoreField;
    // End of variables declaration//GEN-END:variables
}
