/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation;

import com.formdev.flatlaf.FlatClientProperties;
import dto.FoodResponseDto;
import dto.StallResponseDto;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListCellRenderer;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import service.Controller;

/**
 *
 * @author Marco
 */
public class FoodsPanel extends javax.swing.JPanel {

    private final long stallId;
    private final Controller controller = new Controller();
    private final DefaultListModel<FoodResponseDto> listModel = new DefaultListModel<>();
    private JList<FoodResponseDto> foodsList;
    private JScrollPane scrollPane;

    /**
     * Creates new form FoodsPanel
     */
    public FoodsPanel(long stallId) {
        this.stallId = stallId;
        initComponents();
        setupListUI();
        setupFlatLafStyles();
        loadFoodsData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Foods");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(278, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void loadFoodsData() {
        SwingWorker<List<FoodResponseDto>, Void> worker = new SwingWorker<>() {
            @Override
            protected List<FoodResponseDto> doInBackground() throws Exception {
                return controller.getFoodsByStall(stallId);
            }

            @Override
            protected void done() {
                try {
                    List<FoodResponseDto> foods = get();
                    listModel.clear();
                    for (FoodResponseDto food : foods) {
                        listModel.addElement(food);
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(
                            FoodsPanel.this,
                            "Failed to load foods: " + ex.getMessage(),
                            "Error Loading Foods",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        };
        worker.execute();
    }

    private void setupFlatLafStyles() {
        jLabel1.putClientProperty(FlatClientProperties.STYLE, "font: bold +8;");
    }

    private void setupListUI() {
        foodsList = new JList<>(listModel);
        foodsList.setCellRenderer(new FoodListCellRenderer());
        foodsList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        foodsList.setFixedCellHeight(80);

        // FlatLaf specific JList properties
        foodsList.putClientProperty(FlatClientProperties.STYLE, ""
                + "selectionArc: 12;"
                + "cellMargins: 4,8,4,8;");

        scrollPane = new JScrollPane(foodsList);
        scrollPane.putClientProperty(FlatClientProperties.STYLE, "border: 0,0,0,0;");

        // Add scrollPane to panel layout matching StallsPanel layout structure
        setLayout(new BorderLayout(0, 16));
        setBorder(new EmptyBorder(24, 24, 24, 24));

        removeAll(); // Clear default GroupLayout elements
        add(jLabel1, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
    }

    private static class FoodListCellRenderer extends JPanel implements ListCellRenderer<FoodResponseDto> {

        private final JLabel photoLabel = new JLabel();
        private final JLabel nameLabel = new JLabel();
        private final JLabel priceLabel = new JLabel();
        private final Map<String, ImageIcon> iconCache = new HashMap<>();

        public FoodListCellRenderer() {
            setLayout(new BorderLayout(16, 0));
            setBorder(new EmptyBorder(8, 12, 8, 12));

            // Image Thumbnail Container
            photoLabel.setPreferredSize(new Dimension(60, 60));
            photoLabel.setHorizontalAlignment(SwingConstants.CENTER);
            photoLabel.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");

            // Text Metadata Panel
            JPanel textPanel = new JPanel(new GridLayout(2, 1, 0, 2));
            textPanel.setOpaque(false);

            nameLabel.putClientProperty(FlatClientProperties.STYLE, "font: bold +2;");
            priceLabel.putClientProperty(FlatClientProperties.STYLE, "[light]font: -1;");

            textPanel.add(nameLabel);
            textPanel.add(priceLabel);

            add(photoLabel, BorderLayout.WEST);
            add(textPanel, BorderLayout.CENTER);
        }

        @Override
        public Component getListCellRendererComponent(
                JList<? extends FoodResponseDto> list,
                FoodResponseDto food,
                int index,
                boolean isSelected,
                boolean cellHasFocus) {

            nameLabel.setText(food.getName());

            if (food.getPrice() != null) {
                priceLabel.setText(String.format("Price: $%.2f", food.getPrice()));
            } else {
                priceLabel.setText("Price: N/A");
            }

            // Cached Image Scaling to prevent disk I/O lag on scrolls
            String photoPath = food.getFoodPhotoFilePath();
            if (photoPath != null && !photoPath.equals("no_photo_attached")) {
                photoLabel.setIcon(iconCache.computeIfAbsent(photoPath, path -> {
                    File imgFile = new File(path);
                    if (imgFile.exists()) {
                        ImageIcon originalIcon = new ImageIcon(imgFile.getAbsolutePath());
                        Image scaledImg = originalIcon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                        return new ImageIcon(scaledImg);
                    }
                    return null;
                }));
            } else {
                photoLabel.setIcon(null);
            }

            // Theme-aware selection state colors
            if (isSelected) {
                setBackground(list.getSelectionBackground());
                nameLabel.setForeground(list.getSelectionForeground());
                priceLabel.setForeground(list.getSelectionForeground());
            } else {
                setBackground(list.getBackground());
                nameLabel.setForeground(list.getForeground());
                priceLabel.setForeground(UIManager.getColor("Label.disabledForeground"));
            }

            setOpaque(isSelected);
            return this;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
