/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Container;
import java.io.IOException;
import javax.swing.JOptionPane;
import service.UserSession;

/**
 *
 * @author Marco
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainPanel
     */
    public MainFrame() {

        initComponents();
        setLocationRelativeTo(null);
        homeButtonActionPerformed(null);
        addFoodButton.setVisible(UserSession.isLoggedIn());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        adminLoginButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        rankingsButton = new javax.swing.JButton();
        stallsButton = new javax.swing.JButton();
        addFoodButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UM Cafeteria");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        buttonPanel.setBackground(new java.awt.Color(102, 204, 255));

        adminLoginButton.setText("Login");
        adminLoginButton.addActionListener(this::adminLoginButtonActionPerformed);

        homeButton.setText("Home");
        homeButton.addActionListener(this::homeButtonActionPerformed);

        rankingsButton.setText("Rankings");
        rankingsButton.addActionListener(this::rankingsButtonActionPerformed);

        stallsButton.setText("Stalls");
        stallsButton.addActionListener(this::stallsButtonActionPerformed);

        addFoodButton.setText("Add Food");
        addFoodButton.addActionListener(this::addFoodButtonActionPerformed);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stallsButton)
                        .addComponent(rankingsButton)
                        .addComponent(homeButton))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminLoginButton)
                            .addComponent(addFoodButton)
                            .addComponent(logoutButton))
                        .addGap(5, 5, 5)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(homeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rankingsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stallsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(addFoodButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminLoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addGap(19, 19, 19))
        );

        getContentPane().add(buttonPanel);

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));
        mainPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupFlatLafStyles() {
        // Sidebar panel background and clean right border
        buttonPanel.putClientProperty(FlatClientProperties.STYLE, ""
                + "background: $Menu.background;"
                + "border: 0,0,0,1, $Component.borderColor;");

        // Common styling for navigation buttons (rounded corners, padded text, clean focus)
        String navButtonStyle = ""
                + "arc: 10;"
                + "borderWidth: 0;"
                + "focusWidth: 0;"
                + "margin: 8,14,8,14;"
                + "align: left;";

        homeButton.putClientProperty(FlatClientProperties.STYLE, navButtonStyle);
        rankingsButton.putClientProperty(FlatClientProperties.STYLE, navButtonStyle);
        stallsButton.putClientProperty(FlatClientProperties.STYLE, navButtonStyle);

        // Admin button styled with an outline look
        adminLoginButton.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc: 10;"
                + "buttonType: outline;"
                + "margin: 8,14,8,14;");
    }

    private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginButtonActionPerformed
        // TODO add your handling code here:

        AdminLoginPanel adminLogin = new AdminLoginPanel();

        mainPanel.removeAll();
        mainPanel.add(adminLogin);
        mainPanel.revalidate();
        mainPanel.repaint();

    }//GEN-LAST:event_adminLoginButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:

        HomePanel home = new HomePanel();

        mainPanel.removeAll();
        mainPanel.add(home);
        mainPanel.revalidate();
        mainPanel.repaint();

    }//GEN-LAST:event_homeButtonActionPerformed

    private void rankingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingsButtonActionPerformed
        // TODO add your handling code here:

        RankingsPanel rankings = new RankingsPanel();

        mainPanel.removeAll();
        mainPanel.add(rankings);
        mainPanel.revalidate();
        mainPanel.repaint();

    }//GEN-LAST:event_rankingsButtonActionPerformed

    private void stallsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stallsButtonActionPerformed
        // TODO add your handling code here:

        StallsPanel stalls = new StallsPanel();

        mainPanel.removeAll();
        mainPanel.add(stalls);
        mainPanel.revalidate();
        mainPanel.repaint();

    }//GEN-LAST:event_stallsButtonActionPerformed

    private void addFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodButtonActionPerformed
        // TODO add your handling code here:

        AdminAddFoodPanel addFoodPanel = new AdminAddFoodPanel();

        mainPanel.removeAll();
        mainPanel.add(addFoodPanel);
        mainPanel.revalidate();
        mainPanel.repaint();

    }//GEN-LAST:event_addFoodButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:

        if (!UserSession.isLoggedIn()) {
            JOptionPane.showMessageDialog(MainFrame.this, "Not currently logged in.");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(
                MainFrame.this,
                "Are you sure you want to Logout?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            UserSession.token = "";
            new presentation.MainFrame().setVisible(true);

            // 3. Dispose of the current frame
            java.awt.Window topWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (topWindow != null) {
                topWindow.dispose();
            }
        }


    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        com.formdev.flatlaf.FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFoodButton;
    private javax.swing.JButton adminLoginButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton rankingsButton;
    private javax.swing.JButton stallsButton;
    // End of variables declaration//GEN-END:variables
}
