/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation;

import com.formdev.flatlaf.FlatClientProperties;
import dto.FoodResponseDto;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JToggleButton;
import javax.swing.ListCellRenderer;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import service.Controller;

/**
 *
 * @author Marco
 */
  

    public class RankingsPanel extends javax.swing.JPanel {
        
        private enum RankingType {
        PRICE, TASTE, CLEANLINESS
    }

private final Controller controller = new Controller();
    private final DefaultListModel<FoodResponseDto> listModel = new DefaultListModel<>();
    private JList<FoodResponseDto> foodsList;
    private JScrollPane scrollPane;

        /**
         * Creates new form RankingsPanel
         */
        public RankingsPanel() {
initComponents();
        setupListUI();
        setupFlatLafStyles();
        loadRankingData(RankingType.PRICE); // Default display
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Rankings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(255, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void loadRankingData(RankingType type) {
        SwingWorker<List<FoodResponseDto>, Void> worker = new SwingWorker<>() {
            @Override
            protected List<FoodResponseDto> doInBackground() throws Exception {
                switch (type) {
                    case PRICE:
                        return controller.getPriceRanking();
                    case TASTE:
                        return controller.getTasteRanking();
                    case CLEANLINESS:
                        return controller.getCleanlinessRanking();
                    default:
                        return List.of();
                }
            }

            @Override
            protected void done() {
                try {
                    List<FoodResponseDto> foods = get();
                    listModel.clear();
                    for (FoodResponseDto food : foods) {
                        listModel.addElement(food);
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(
                            RankingsPanel.this,
                            "Failed to load ranking data: " + ex.getMessage(),
                            "Error Loading Rankings",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        };
        worker.execute();
    }

private void setupFlatLafStyles() {
        jLabel1.putClientProperty(FlatClientProperties.STYLE, "font: bold +8;");
    }

        private void setupListUI() {
        foodsList = new JList<>(listModel);
        foodsList.setCellRenderer(new RankingListCellRenderer());
        foodsList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        foodsList.setFixedCellHeight(80);

        // FlatLaf specific list properties
        foodsList.putClientProperty(FlatClientProperties.STYLE, ""
                + "selectionArc: 12;"
                + "cellMargins: 4,8,4,8;");

        // Double-click to open details
        foodsList.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2 && SwingUtilities.isLeftMouseButton(e)) {
                    int index = foodsList.locationToIndex(e.getPoint());
                    if (index != -1) {
                        FoodResponseDto selectedFood = listModel.getElementAt(index);
                        Container parentContainer = RankingsPanel.this.getParent();

                        if (parentContainer != null) {
                            FoodItemPanel foodItemPanel = new FoodItemPanel(selectedFood, "Rankings");
                            parentContainer.removeAll();
                            parentContainer.add(foodItemPanel);
                            parentContainer.revalidate();
                            parentContainer.repaint();
                        }
                    }
                }
            }
        });

        scrollPane = new JScrollPane(foodsList);
        scrollPane.putClientProperty(FlatClientProperties.STYLE, "border: 0,0,0,0;");

// Header Panel (Title Left, Toggle Buttons Right)
JPanel topPanel = new JPanel(new BorderLayout());
topPanel.setOpaque(false);

// Segmented Toggle Button Group for Switching Rankings
JToggleButton priceBtn = new JToggleButton("Price");
JToggleButton tasteBtn = new JToggleButton("Taste");
JToggleButton cleanlinessBtn = new JToggleButton("Cleanliness");

priceBtn.setSelected(true); // Default selection

// Assign segment position client properties
priceBtn.putClientProperty(FlatClientProperties.STYLE, "segmentPosition: first");
tasteBtn.putClientProperty(FlatClientProperties.STYLE, "segmentPosition: middle");
cleanlinessBtn.putClientProperty(FlatClientProperties.STYLE, "segmentPosition: last");

// Group buttons logically for single selection
ButtonGroup buttonGroup = new ButtonGroup();
buttonGroup.add(priceBtn);
buttonGroup.add(tasteBtn);
buttonGroup.add(cleanlinessBtn);

// Wire action listeners
priceBtn.addActionListener(e -> loadRankingData(RankingType.PRICE));
tasteBtn.addActionListener(e -> loadRankingData(RankingType.TASTE));
cleanlinessBtn.addActionListener(e -> loadRankingData(RankingType.CLEANLINESS));

// Container panel for the segmented button control
JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 0, 0));
buttonPanel.setOpaque(false);

// Set FlatLaf style on the container to enforce segment grouping
buttonPanel.putClientProperty(FlatClientProperties.STYLE, "buttonType: segmentedOnly;");

buttonPanel.add(priceBtn);
buttonPanel.add(tasteBtn);
buttonPanel.add(cleanlinessBtn);

topPanel.add(jLabel1, BorderLayout.WEST);
topPanel.add(buttonPanel, BorderLayout.EAST);

        // Reconfigure main panel layout
        setLayout(new BorderLayout(0, 16));
        setBorder(new EmptyBorder(24, 24, 24, 24));

        removeAll();
        add(topPanel, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
    }

        private static class RankingListCellRenderer extends JPanel implements ListCellRenderer<FoodResponseDto> {

        private final JLabel rankLabel = new JLabel();
        private final JLabel photoLabel = new JLabel();
        private final JLabel nameLabel = new JLabel();
        private final JLabel priceLabel = new JLabel();
        private final Map<String, ImageIcon> iconCache = new HashMap<>();

        public RankingListCellRenderer() {
            setLayout(new BorderLayout(12, 0));
            setBorder(new EmptyBorder(8, 12, 8, 12));

            // Rank Number Badge (e.g., #1, #2, #3)
            rankLabel.setPreferredSize(new Dimension(36, 60));
            rankLabel.setHorizontalAlignment(SwingConstants.CENTER);
            rankLabel.putClientProperty(FlatClientProperties.STYLE, "font: bold +3; foreground: $Label.disabledForeground;");

            // Image Thumbnail
            photoLabel.setPreferredSize(new Dimension(60, 60));
            photoLabel.setHorizontalAlignment(SwingConstants.CENTER);
            photoLabel.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");

            // Text Info Panel
            JPanel textPanel = new JPanel(new GridLayout(2, 1, 0, 2));
            textPanel.setOpaque(false);

            nameLabel.putClientProperty(FlatClientProperties.STYLE, "font: bold +2;");
            priceLabel.putClientProperty(FlatClientProperties.STYLE, "[light]font: -1;");

            textPanel.add(nameLabel);
            textPanel.add(priceLabel);

            JPanel leftContainer = new JPanel(new BorderLayout(8, 0));
            leftContainer.setOpaque(false);
            leftContainer.add(rankLabel, BorderLayout.WEST);
            leftContainer.add(photoLabel, BorderLayout.CENTER);

            add(leftContainer, BorderLayout.WEST);
            add(textPanel, BorderLayout.CENTER);
        }

        @Override
        public Component getListCellRendererComponent(
                JList<? extends FoodResponseDto> list,
                FoodResponseDto food,
                int index,
                boolean isSelected,
                boolean cellHasFocus) {

            rankLabel.setText("#" + (index + 1));
            nameLabel.setText(food.getName());

            if (food.getPrice() != null) {
                priceLabel.setText(String.format("Price: ₱%.2f", food.getPrice()));
            } else {
                priceLabel.setText("Price: N/A");
            }

            // Image scaling with cache
            String photoPath = food.getFoodPhotoFilePath();
            if (photoPath != null && !photoPath.equals("no_photo_attached")) {
                photoLabel.setIcon(iconCache.computeIfAbsent(photoPath, path -> {
                    File imgFile = new File(path);
                    if (imgFile.exists()) {
                        ImageIcon originalIcon = new ImageIcon(imgFile.getAbsolutePath());
                        Image scaledImg = originalIcon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                        return new ImageIcon(scaledImg);
                    }
                    return null;
                }));
            } else {
                photoLabel.setIcon(null);
            }

            // Selection styles
            if (isSelected) {
                setBackground(list.getSelectionBackground());
                nameLabel.setForeground(list.getSelectionForeground());
                priceLabel.setForeground(list.getSelectionForeground());
                rankLabel.setForeground(list.getSelectionForeground());
            } else {
                setBackground(list.getBackground());
                nameLabel.setForeground(list.getForeground());
                priceLabel.setForeground(UIManager.getColor("Label.disabledForeground"));
                rankLabel.setForeground(UIManager.getColor("Label.disabledForeground"));
            }

            setOpaque(isSelected);
            return this;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
